spring:
  application:
    name: dd-ai-agent
  profiles:
    active: local
  #redis
  data:
    redis:
      host: localhost
      port: 6379
  config:
    import:
      - "optional:nacos:spring.ai.alibaba.configurable.prompt.json"
  nacos:
    username: nacos
    password: nacos
  ai:
#    mcp:
#      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
    nacos:
      prompt:
        template:
          enabled: true  #开启动态模板功能

mybatis:
  primary:
    mapper-locations: classpath:mapper/mysql/*.xml
    type-aliases-package: com.dd.ddaiagent.entity
    configuration:
      map-underscore-to-camel-case: true
  secondary:
    mapper-locations: classpath:mapper/postgresql/*.xml
    type-aliases-package: com.dd.ddaiagent.entity
server:
  port: 8123
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.dd.ddaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug