spring:
  ai:
    mcp:
      server:
        name: dd-image-search-mcp-server
        version: 0.0.1
        type: SYNC
        # sse
        stdio: false
    alibaba:
      mcp:
        nacos:
          server-addr: localhost:8848
          namespace: public
          username: nacos
          password: nacos
          registry:
            enabled: true